name: pywsindy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11.15
  - pip
  - jupyterlab
  - pip:
    - ipython==8.12.3
    - matplotlib==3.11.0
    - numpy==2.4.6
    - scipy==1.18.0
    - symengine==0.14.1
    - torch
    - torchvision
    - torchaudio
    - tqdm==4.67.3
